### ISSUE TITLE
Test set

### ISSUE THREAD

**Issue by nicoring** [rshkv/wort2vek#2]
Collection of types and their test-set size:

### Semantic
- [ ] Capitals of German federal states
- [ ] Country - Capital
- [ ] Country - Currency
- [ ] Country - Language
- [ ] Country - head of state
- [ ] Country - Demomym
- [ ] Company - Product
- [ ] Company - CEO
- [ ] Famous person - job
- [ ] Man-Woman

#### General
- [ ] Opposite
- [ ] Adjectives (positive, comparative, superlative)

#### Verbs
- [ ] tenses
- [ ] conjugation
- [ ] Singular - Plural

#### Nouns
- [ ] Singular - Plural
- [ ] declension

**Comment by nicoring** [comment]
@rshkv We must define how we deal with declension and conjugation, since there are a lot of possibilities in German.

**Comment by nicoring** [comment]
## Original Paper

To measure the quality of the word vectors, [Mikolov et al.](https://papers.nips.cc/paper/5021-distributed-representations-of-words-and-phrases-and-their-compositionality.pdf) use semantic and syntactic questions, numbered 8869 and 10675, respectively. For each type (e.g. _semantic_), they have categories (e.g. _Common capital city_). An overview of the categories they use is below:

### Semantic

| Type of relationships | Word pair 1 |            | Word pair 2 |               |
| --------------------: | ----------: | ---------- | ----------: | ------------- |
|   Common capital city |      Athens | Greece     |        Oslo | Norway        |
|    All capital cities |      Astana | Kazakhstan |      Harare | Zimbabwe      |
|              Currency |      Angola | kwanza     |        Iran | rial          |
|         City-in-state |     Chicago | Illinois   |    Stockton | California    |
|             Man-Woman |     brother | sister     |    grandson | granddaughter |

### Syntactic

| Type of relationships | Word pair 1 |             | Word pair 2 |           |
| --------------------: | ----------: | :---------- | ----------: | --------- |
|   Adjective to adverb |    apparent | apparently  |       rapid | rapdily   |
|              Opposite |    possibly | impossibily |     ethical | unethical |
|           Comparative |       great | greater     |       tough | tougher   |
|           Superlative |        easy | easiest     |       lucky | luckiest  |
|    Present Participle |       think | thinking    |        read | reading   |
| Nationality adjective | Switzerland | Swiss       |    Cambodia | Cambodian |
|           Paste tense |     walking | walked      |    swimming | swam      |
|          Plural nouns |       mouse | mice        |      dollar | dollars   |
|          Plural verbs |        work | works       |       speak | speaks    |

**Comment by rshkv** [comment]
### Adjectives
I propose we don't use all 6 directions but only go from positives. I.e.:
- [ ] Positive ➝ Comparative (_groß_ ➝ _größer_)
- [ ] Positive ➝ Superlative (_groß_ ➝ _größten_)

**Comment by rshkv** [comment]
### Verbs

With verbs there is too much we can do, here's a comprehensive list for _denken_:

- infinitive ➝ participle
  - ➝ _denkend_		(active)
  - ➝ _gedacht_	(passive)
- infinitive ➝ imperative
  - ➝ _denk_		(1st person)
  - ➝ ...
- infinitive ➝ present
  - ➝ _denke_		(present, 1st person)
  - ➝ ...
- infinitive ➝ past
  - ➝ _dachte_		(past 1st person)
  - ➝ ...
- infinitive ➝ perfect (_Konjunktiv Perfekt_)
- infinitive ➝ past perfect (_Plusquamperfekt_)
- infinitive ➝ futur (I) (_Futur I_)
- infinitive ➝ future perfect (_Futur II_)
- infinitive ➝ present subjunctive I (_Konjunktiv I_)
- infinitive ➝ present subjunctive II (_Konjunktiv II_)
- infinitive ➝ past subjunctive I (_Konjunktiv Perfekt_)
- infinitive ➝ past subjunctive II (_Konjunktiv Plusquamperfekt_)
- infinitive ➝ future subjunctive I (_Konjunktiv Futur I_)
- infinitive ➝ future subjunctive II (_Konjunktiv Futur II_)
- ...

Obviously, we don't need to cover all of them. In fact, we can't, because the more complex conjugations are composites (e.g., _hätte gedacht_, _werde gedacht haben_).

For now, I think we only have to cover the following to prove quality:

- [ ] infinitive ➝ passive participle (_denken_ ➝ _gedacht_)
- [ ] infinitive ➝ present
      - [ ] 1st person (_denke_)
      - [ ] 2nd person (_denkst_)
      - [ ] 3rd person (_denkt_)
- [ ] infinitive ➝ past
      - [ ] 1st person (_dachte_)
      - [ ] 2nd person (_dachtest_)
      - [ ] 3rd person (_dachte_)

Once we start testing plural person, we might also encounter strange behavior: E.g., _denken_ can be infinitive, 1st person plural, 3rd person plural.

**Comment by rshkv** [comment]
@nicoring Can we close this issue?

**Comment by nicoring** [comment]
I would propose to test the following:

### Verbs:

- Infinitiv -> Partizip I
sehen -> gesehen

- 1.Person Singular Präsenz -> 1. Person Plural Präsenz
sehe -> sehen

- 1.Person Singular Präsenz -> 2. oder 3. Person Singular Präsenz
sehe -> siehst,sieht


- 1.Person Singular Präsenz -> 1. und 3. oder 2. Person Singular Präteritum
sehe -> sah,sahst

- 1.und 3. Person Plural Präsenz -> 1. und 3. Person Plural Präteritum
sehen -> sahen

### Nouns
- Nominativ Singular -> Nominativ Plural
Buch -> Bücher

- Nominativ Singular -> Genitiv Singular
Buch -> Buches

### Adjectives
- Positiv -> Komparativ
schnell -> schneller

- Positiv -> Superlativ
schnell -> schnellsten

@rshkv If you approve this, I will build the test set in this way

**Comment by nicoring** [comment]
I am not  sure if we should use the first person as a base for all pairs. Maybe the third person is more suitable, because it is used more often in written text.

**Comment by rshkv** [comment]
I agree with your point on 3rd person. Maybe build test cases for both singular and plural?
How did Mikolov test verbs? I think that would be easier to 'justify' for us.

**Comment by nicoring** [comment]
They test only present and past of verbs. I think we can't really base on this because in English there are only two forms for verbs in present and one for the past.


On Sun, Jan 15, 2017 at 7:32pm, Willi Raschkowski < notifications@github.com [notifications@github.com] > wrote:
I agree with your point on 3rd person. Maybe build test cases for both singular and plural?
How did Mikolov test verbs? I think that would be easier to 'justify' for us.

**Comment by rshkv** [comment]
| Person        | German (present) | Englisch (present) | German (past) | Englisch (past) |
| ------------- | ---------------- | ------------------ | ------------- | --------------- |
| **1st**       | bin              | am                 | war           | was             |
| **2nd**       | bist             | are                | warst         | were            |
| **3rd**       | ist              | is                 | war           | was             |
| **1st (pl.)** | sind             | are                | waren         | were            |
| **2nd (pl.)** | seid             | are                | wart          | were            |
| **3rd (pl.)** | sind             | are                | waren         | were            |

**Comment by rshkv** [comment]
I think that'd be fine. We can keep it simple for now and add more later.

**Comment by nicoring** [comment]
Verbs
sieht -> sehen
sieht -> gesehen (only if not equal to another form)
sieht -> sah
sieht -> sahen
