### ISSUE TITLE
Finish evaluation

### ISSUE THREAD

**Issue by rshkv** [rshkv/wort2vek#4]
Create plot for variables:
* sample size
* vector size
* epochs

Also try variables:
- [ ] skip-gram/cbow
- [ ] windows size
- [ ] drop infrequent words

**Comment by rshkv** [comment]
Create Wiki article with results, cf. https://github.com/rshkv/goethe/blob/master/evaluation/evaluation.ipynb.

**Comment by nicoring** [comment]
We'll now evaluate the following for skip gram and cbow:

- vector size 200, 300, 400, 500
- window 5, 10, 20

with 10 million randomly chosen sentences from leipzig corpus and 10 training epochs.
